export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_RECEIVE = 'FETCH_MOVIES_RECEIVE';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_CURRENT_MOVIE_RECEIVE = 'FETCH_CURRENT_MOVIE_RECEIVE';
export const CHANGE_TYPE_OF_SEARCH = 'CHANGE_TYPE_OF_SEARCH';